/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionespedizioni;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author caggi
 */
public class VisBord extends javax.swing.JFrame {

    Connection conn = null;
    String url = "jdbc:postgresql://localhost/gestioneSpedizioni";
    String user = "postgres";
    String pass = "root";

    private String nome;
    private String cognome;
    private ArrayList<Bordero> ab = new ArrayList<>();

    /**
     * Creates new form VisBord
     */
    public VisBord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TOS", "DDT", "N COLLI", "MITT", "INDIRIZZO", "DEST", "INDIRIZZO", "TEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Bordero> bord = new ArrayList<>();

        DefaultTableModel model = (DefaultTableModel) tab.getModel();

        Integer dim = this.getAb().size();
        Integer k = 1;
        //SalvaBord sb = new SalvaBord();
        for (Integer i = 0; i < dim; i++) {
            SalvaBord sb = new SalvaBord();
            if (this.getAb().get(i).getA().getCognome().equalsIgnoreCase(this.getCognome()) && this.getAb().get(i).getA().getNome().equalsIgnoreCase(this.getNome())) {
                Bordero vbord = new Bordero();
                Spedizioni s = new Spedizioni();
                Autisti a = new Autisti();
                Macchina m = new Macchina();

                k++;
                model.addRow(new Object[]{this.getAb().get(i).getS().getTos().toUpperCase(), this.getAb().get(i).getS().getNddt(), this.getAb().get(i).getS().getNc(), this.getAb().get(i).getS().getMitt().getRagSoc().toUpperCase(), this.getAb().get(i).getS().getMitt().getIndirizzo().toUpperCase() + ", " + this.getAb().get(i).getS().getMitt().getCap(), this.getAb().get(i).getS().getDest().getRagSoc().toUpperCase(), this.getAb().get(i).getS().getDest().getIndirizzo().toUpperCase() + ", " + this.getAb().get(i).getS().getDest().getCap(),this.getAb().get(i).getS().getTel()});
                /*a.setNome(this.getAb().get(i).getA().getNome());
                a.setCognome(this.getAb().get(i).getA().getCognome());
                s.setDataCons(this.getAb().get(i).getS().getDataCons());
                s.setId(this.getAb().get(i).getS().getId());
                m.setTarga(this.getAb().get(i).getM().getTarga());
                vbord.setA(a);
                vbord.setS(s);
                vbord.setM(m);
                */
            }

        }
        tab.setRowHeight(tab.getRowHeight() * k);


    }//GEN-LAST:event_formComponentShown

    public ArrayList<Bordero> getAb() {
        return ab;
    }

    public void setAb(ArrayList<Bordero> ab) {
        this.ab = ab;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisBord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisBord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
